#learn about numpy

In [42]:
import numpy as np

In [43]:
##creating array from list

In [44]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)


arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ",arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


##List vs numpy array

In [45]:
py_list = [1,2,3]
print("Python list multiplication: ",py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python array multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.0422055721282959

 Numpy operation time:  0.0036764144897460938


#creating arrays from scratch

In [46]:
zeroes = np.zeros((3,3))
print("zeroes array: \n", zeroes)

ones = np.ones((2,2))
print("ones array: \n", ones)

full = np.full((3,3),5)
print("full array: \n", full)

random = np.random.random((2,4))
print("random array: \n", random)

sequence = np.arange(0,10,2)
print("sequence array: \n", sequence)


zeroes array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1.]
 [1. 1.]]
full array: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
random array: 
 [[0.61882982 0.39363093 0.25468967 0.40940998]
 [0.99022794 0.35503261 0.29052296 0.38513283]]
sequence array: 
 [0 2 4 6 8]


#Vector , Matrix , Tensor

In [47]:
vector = np.array([1,2,3,4,5])
print("Vector: \n", vector)

Matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix: \n", Matrix)

Tensor = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print("Tensor: \n", Tensor)


Vector: 
 [1 2 3 4 5]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#Array Properties

In [50]:
arr = np.array([[1,2,3],
                [4,5,6.9]])
print("Array:\n", arr)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)




Array:
 [[1.  2.  3. ]
 [4.  5.  6.9]]
Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  float64


#Array Reshaping

In [57]:
arr = np.arange(12)
print("Original array: ",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array: ", reshaped)

flattened = arr.flatten()
print("\n Flattened array: ",flattened)

#ravel (returns view instead of copy)
raveled = reshaped.ravel()
print("\n raveled array: ", raveled)

#Transpose
transpose = reshaped.T
print("\n Transposed array: ", transpose)

#Transposing an 2Darray
arr_2 = np.array([[1,2,3,4], [5,6,7,8]])
print("\n Array_2 : ", arr_2)
transpose_2D = arr_2.T
print("\n Transpose_2D: ", transpose_2D)





Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

 Array_2 :  [[1 2 3 4]
 [5 6 7 8]]

 Transpose_2D:  [[1 5]
 [2 6]
 [3 7]
 [4 8]]
