#Numpy arrays operations

In [3]:
import numpy as np

In [4]:
arr = ([1,2,3,4,5,6,7,8,9,10])
print("Array: ", arr)
print("Basic slicing: ",arr[3:8])
print("With step: ", arr[2:10:2])
print("Negative indexing: ", arr[-4])


Array:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Basic slicing:  [4, 5, 6, 7, 8]
With step:  [3, 5, 7, 9]
Negative indexing:  7


In [5]:
arr_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Entire Array: ", arr_2D)
print("Specific element: ",arr_2D[1,2])
print("Entire row: ", arr_2D[1])
print("Entire col: ", arr_2D[:,1])


Entire Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element:  6
Entire row:  [4 5 6]
Entire col:  [2 5 8]


#Sorting

In [9]:
unsorted = np.array([1,3,5,2,3,7,9,3,9,7,2])
print("Sorted array: ", np.sort(unsorted))

arr_2D_unsorted = np.array([[3,1],[2,6],[5,9]])
print("Entire array is: ", arr_2D_unsorted)
print("Sorted 2D array by column: ",np.sort(arr_2D_unsorted, axis = 0))


Sorted array:  [1 2 2 3 3 3 5 7 7 9 9]
Entire array is:  [[3 1]
 [2 6]
 [5 9]]
Sorted 2D array by column:  [[2 1]
 [3 6]
 [5 9]]


#Filter

In [10]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ",even_numbers)

Even numbers:  [ 2  4  6  8 10]


#Filter with mask

In [14]:
arr_no = np.array([1,2,3,4,5,6,7,8,9,10])
mask = arr_no > 5
print("Numbers greater than 5: ", numbers[mask])
#in place of mask i can take any variable

yash = arr_no < 5
print("Numbers less than 5: ", numbers[yash])

Numbers greater than 5:  [ 6  7  8  9 10]
Numbers less than 5:  [1 2 3 4]


#Fancy indexing vs np.where()

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,2,4]
print(numbers[indices])

#np..wher is typically used with a condition
where_result = np.where(numbers > 5)
print(where_result)
print("np_where: ", numbers[where_result]) #here it only print the true values


[1 3 5]
(array([5, 6, 7, 8, 9]),)
np_where:  [ 6  7  8  9 10]


In [ ]:
# Ensure 'numbers' is defined
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

condition_array = np.where(numbers > 5 , numbers * 2 , numbers)
#condition_array = np.where(numbers > 5 , "true" , "false")
print(condition_array)
#here np.where() acts as if else loop where condiion is true it will execute 
# first statement otherwise second statement

[ 1  2  3  4  5 12 14 16 18 20]


In [ ]:
#executing np.where() with condition just like above where numbers array is declared in above cell
result = np.where(num > 6 , num * 3 , num)
print(result)

#executing if-else like here do not need np.where()
if np.any(numbers > 5):
#if np.all(numbers > 5):
    print(numbers * 2)
else:
    print(numbers)

[ 1  2  3  4  5  6 21 24 27 30]
[ 2  4  6  8 10 12 14 16 18 20]


#Adding and removing data 

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])\

combined = np.concatenate((arr1 , arr2))
print(combined)

[1 2 3 4 5 6]


#Array compatibility

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6,5])
c = np.array([7,8,9])

print("Compatibility shape :", a.shape == b.shape)


Compatibility shape : False


In [25]:
original = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack([original , new_row])
print("Original array: ",original)
print("With new Row: ",with_new_row)

new_col = np.array([[7] , [8]])
with_new_col = np.hstack([original , new_col])
print("\nOriginal array: ",original)
print("With new Col: ",with_new_col)

Original array:  [[1 2]
 [3 4]]
With new Row:  [[1 2]
 [3 4]
 [5 6]]

Original array:  [[1 2]
 [3 4]]
With new Col:  [[1 2 7]
 [3 4 8]]


In [32]:
arr = np.array([1,2,3,4,5])
delete = np.delete(arr , 2)
#delete = np.delete(arr,[0,3,4])
# delete = np.delete(arr, range(0, 3))
print("Array after deletion :",delete)

Array after deletion : [1 2 4 5]
